### ISSUE TITLE
user access

### ISSUE THREAD

**Issue by admiraltidebringer** [cccaaannn/telegram_youtube_downloader#2]
hello
can you add a feature to control user access with Chat ID?
it will be very useful.

**Comment by cccaaannn** [comment]
You mean to block certain people, or to block everyone by default and grant access to certain people.

**Comment by admiraltidebringer** [comment]
i think it will be great if we can grant access to certain people.

**Comment by cccaaannn** [comment]
I will probably add something like that, but I want it to be a optional thing so let me think about a great way to implement that.

**Comment by cccaaannn** [comment]
Hi, I finally had some time to work on this.
I added some ways for authorization, you should be able to do what you want with that.
Check the authorization section on docs/configuration, it also has examples.
