### ISSUE TITLE
Use GPU on FFMPEG

### ISSUE THREAD

**Issue by ElbertePlinio** [cccaaannn/telegram_youtube_downloader#3]
Can I use my dedicated GPU instead of my CPU for the FFMPEG related tasks?

**Comment by cccaaannn** [comment]
Hi, I never tested with gpu but it should be about ffmpeg installation.
I am very busy on weekdays 😅, but I will check it when I have time.

**Comment by cccaaannn** [comment]
Hi, I tested hardware acceleration and if your system supports it than it should be working with a simple config change.
I added [this wiki page](https://github.com/cccaaannn/telegram_youtube_downloader/wiki/Hardware-Acceleration) for this.
