### ISSUE TITLE
Connection issues while using vps

### ISSUE THREAD

**Issue by VanshSahay** [cccaaannn/telegram_youtube_downloader#5]
Im using a vps to run the bot and while using links from instagram, soundcloud, etc it shows site not supported. I've attached the errors shown on cli. The code seems to be working for websites like youtube and tiktok on a vps and for everything while running it normally outside of the vps
![image](https://github.com/cccaaannn/telegram_youtube_downloader/assets/92102479/ef23effc-6a6e-4b23-bde0-872814b016bf)
![image](https://github.com/cccaaannn/telegram_youtube_downloader/assets/92102479/d02d5ca0-8aa8-45ef-bd1f-4a38dcd504d8)

**Comment by cccaaannn** [comment]
If you can download the same content when you run it outside the vps then it could be about the region of the vps. Can you try a different region or maybe different provider.

**Comment by VanshSahay** [comment]
I fixed the issue thank you, actually it was because of yt-dlp which couldn't connect to Instagram from inside a server (Instagram blocks almost all database IPs), I passed cookies to yt-dlp and it worked! 

Amazing code btw, really useful and professional
Thank you🤝

**Comment by cccaaannn** [comment]
Thanks for the kind words.

**Comment by lyaxsh** [comment]
> I fixed the issue thank you, actually it was because of yt-dlp which couldn't connect to Instagram from inside a server (Instagram blocks almost all database IPs), I passed cookies to yt-dlp and it worked!
> 
> Amazing code btw, really useful and professional Thank you🤝

hey, how did you manage to pass cookies to yt-dlp, please tell the cmd

**Comment by cccaaannn** [comment]
I never tested with cookies, but you can pass yt dlp options from [config file](https://github.com/cccaaannn/telegram_youtube_downloader/wiki/Configurations#audio_options-and-video_options).

It looks like yt dlp needs a [file](https://github.com/ytdl-org/youtube-dl/blob/5975d7bb96095fae7c35e7cfcd819255a5b57087/youtube_dl/YoutubeDL.py#L244) for cookies, you probably need to map a volume for the cookie file.

`/cookies:/telegram_youtube_downloader/cookies`

Than pass it to config file.

`configs/config.yaml`
```yaml
  video_options:
    postprocessors: 
      - key: "FFmpegVideoConvertor"
        preferedformat: "mp4"
    format: "bestvideo+bestaudio"
    noplaylist: true
    cookiefile: "/telegram_youtube_downloader/cookies/cookie.txt"
```
