### ISSUE TITLE
Please integrate Allowed UserIDs

### ISSUE THREAD

**Issue by tomatoinaction** [cccaaannn/telegram_youtube_downloader#6]
Please integrate UserID filtering, so you can define via ENV e.g. only UserID 12345678 can chat with the bot

**Comment by cccaaannn** [comment]
Hi, you can already do that with [authorization_options](https://github.com/cccaaannn/telegram_youtube_downloader/wiki/Configurations#authorization_options).

**Comment by tomatoinaction** [comment]
okay thanks but how can i do this in docker persistent? like in ENV or with LABELS?

**Comment by cccaaannn** [comment]
You should map the config folder to a folder on the host machine and provide a custom config file.

Copy the config file an put it on a path, add your path to this command.
```
sudo docker run -d --name telegram_youtube_downloader --restart unless-stopped \
-e TELEGRAM_BOT_KEY=<TELEGRAM_BOT_KEY> \
-v <YOUR_CONFIGS_PATH>:/telegram_youtube_downloader/telegram_youtube_downloader/configs \
cccaaannn/telegram_youtube_downloader:latest
```

**Comment by tomatoinaction** [comment]
No thats possible security breach.

But i can create volume and mount it to /config? and then set in config
like $variable this should then be possible to do with ENV in docker config?

Can Kurt ***@***.***> schrieb am Fr., 13. Okt. 2023, 17:08:

**Comment by cccaaannn** [comment]
What is your security concern with volume mapping, there are no secrets in the config.

You can use docker config, but I didn't understand what you want to do with env. If you want to set stuff in the config file with env its not supported right now because config file is a static file and does not checks for the env but I'm planning to add that in the future. If you want something like that you might use envsubst before running the container.

If you just want to use docker config then this should work.
```
docker service create --name telegram_youtube_downloader \
--config src=my_config,target="telegram_youtube_downloader/telegram_youtube_downloader/configs/config.yaml" \
-e TELEGRAM_BOT_KEY=<TELEGRAM_BOT_KEY> \
cccaaannn/telegram_youtube_downloader:latest
```

**Comment by tomatoinaction** [comment]
ah come on ... not working like expected

```
2023-10-14T14:16:52.526289619Z [TelegramBot] [ERROR] (Bot:xxx:dispatcher) (2023-10-14 14:16:52) User: {'first_name': xxx', 'language_code': 'de', 'is_bot': False, 'id': xxxxxxx, 'username': 'yyy'} | Function: help | Args: []
2023-10-14T14:16:52.526317380Z Traceback (most recent call last):
2023-10-14T14:16:52.526320740Z   File "/telegram_youtube_downloader/telegram_youtube_downloader/decorators/telegram_bot_error_handler.py", line 12, in wrapper
2023-10-14T14:16:52.526323700Z     func(*args, **kwargs)
2023-10-14T14:16:52.526325900Z   File "/telegram_youtube_downloader/telegram_youtube_downloader/decorators/telegram_bot_command_interceptor.py", line 16, in wrapper
2023-10-14T14:16:52.526353300Z     authorization_options = ConfigUtils.read_cfg_file()["telegram_bot_options"]["authorization_options"]
2023-10-14T14:16:52.526356380Z KeyError: 'authorization_options'
```

![image](https://github.com/cccaaannn/telegram_youtube_downloader/assets/44731882/ca583aa8-f443-4842-b758-c34110873daa)

**Comment by cccaaannn** [comment]
I tested with docker config it works for me, how did you tried it.

**Comment by tomatoinaction** [comment]
what information do you need?
i pulled the image and deployed it - so far was working.
now i made a persistent volume and mounted it so i can edit the config file.
then i edit the config as you can see above and this error showed up when restarting then container ...

**Comment by cccaaannn** [comment]
I can understand from your screenshot your indentation is wrong with the config file, `authorization_options` should be inside `telegram_bot_options`.

**Comment by tomatoinaction** [comment]
this and the userid cannot be in "" 
i wonder how vim can show me the lines?
thanks!
